[package]
name = "wio_clock"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.5"
micromath  = "2.0.0"
wio_referee = {"path" = "../wio_referee"}
embedded-graphics = "0.7.1"
