[package]
authors = ["saruyoshida"]
name = "discrete_white_noise"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.32.3", default-features = false, features  =   [  "libm" ]}
micromath = "2.0.0"

