[package]
authors = ["saruyoshida"]
name = "filter_base"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.33.0", default-features = false, features  =   [  "libm" ]}
micromath = "2.1.0"

