[package]
name = "debug_action_integral_box"
version = "0.1.0"
edition = "2021"

[dependencies]
action_integral_box = {"path" = "../../action_integral_box"}

[[example]]
name = "debug_action_integral_box"



