[package]
authors = ["saruyoshida"]
name = "emb_linegraph"
version = "0.1.0"
edition = "2021"

[dependencies]
micromath = "2.0.0"
embedded-graphics = "0.7.1"
emb_bargraph = {"path" = "../emb_bargraph"}
emb_linetrim = {"path" = "../emb_linetrim"}

