[package]
name = "draw-robot-sim-ellipses"
version = "0.1.0"
edition = "2021"

[dependencies]
wio_terminal = "0.4"
cortex-m = "0.6"
cortex-m-rt = { version = "0.6", optional = true }
panic-halt = "0.2"
emb_bargraph = {"path" = "../../../../emb_bargraph"}
emb_covargraph = {"path" = "../../../../emb_covargraph"}
emb_linegraph = {"path" = "../../../../emb_linegraph"}
emb_shapegraph = {"path" = "../../../../emb_shapegraph"}
mv_kalmanfilter = {"path" = "../../mv_kalmanfilter"}
discrete_white_noise = {"path" = "../../discrete_white_noise"}
robot2d = {"path" = "../robot2d"}

[[example]]
name = "draw-robot-sim-ellipses"



