[package]
authors = ["saruyoshida"]
name = "robotukffn"
version = "0.1.0"
edition = "2021"

[dependencies]
micromath = "2.0.0"
nalgebra = { version = "0.32.3", default-features = false, features  =   [  "libm" ]}
robotukfsim = {"path" = "../robotukfsim"}


