[package]
authors = ["saruyoshida"]
name = "filter_supply_example"
version = "0.1.0"
edition = "2021"

[dependencies]
mv_kalmanfilter = {"path" = "../../multi_variate_filter/mv_kalmanfilter"}
filter_base = {"path" = "../../filter_base"}
nalgebra = { version = "0.33.0", default-features = false, features  =   [  "libm" ]}
discrete_white_noise = {"path" = "../../multi_variate_filter/discrete_white_noise"}
ms_sigmapoints = {"path" = "../../unscented_filter/ms_sigmapoints"}
us_kalmanfilter = {"path" = "../../unscented_filter/us_kalmanfilter"}
us_transform = {"path" = "../../unscented_filter/us_transform"}
micromath = "2.1.0"

